### ISSUE TITLE
Object ids not included

### ISSUE THREAD

**Issue by jpgeek** [y-yagi/to_fixture#2]
Thanks for this.

It looks like the object ids are not included by design.  Is there a reason for this?  When dumping related tables, how are the references maintained?

**Comment by y-yagi** [comment]
Thank you for using! 

In my opinion, association is better to define the label rather than the id, so id does not include. But I know it's is inconvenient. I will consider include id.

**Comment by jpgeek** [comment]
Thanks very much for the reply and for explaining your decision.  Cheers!
